---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: app-sre-pipeline-trigger-binding
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.url)
  - name: git-revision
    value: $(body.head_commit.id)
  - name: git-repo-name
    value: $(body.repository.name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: app-sre-pipeline-trigger-template
spec:
  params:
  - name: git-repo-url
    description: The git repository url
  - name: git-revision
    description: The git revision
    default: master
  - name: git-repo-name
    description: The name of the deployment to be created / patched

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: app-sre-build-push-pipeline-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: app-sre-build-push-pipeline
      params:
      - name: repo-url
        value: $(tt.params.git-repo-url)
      - name: rev-id
        value: $(tt.params.git-revision)
      - name: context-dir
        value: 'dockerfiles'
      - name: image-registry
        value: 'image-registry.openshift-image-registry.svc:5000'
      - name: image-name
        value: $(tt.params.git-repo-name)
      - name: name-space
        value: 'app-sre-cicd'
      - name: remote-registry
        value: 'quay.io'
      - name: remote-org
        value: 'arilivigni'
      workspaces:
      - name: shared-workspace
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: app-sre-pipeline-trigger
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: app-sre-pipeline-trigger-binding
  template:
    name: app-sre-pipeline-trigger-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: app-sre-github-listener-interceptor
spec:
  serviceAccountName: pipeline
  triggers:
  - name: github-listener
    bindings:
      - ref: app-sre-pipeline-trigger-binding
    template:
      name: app-sre-pipeline-trigger-template
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener:  app-sre-github-listener-interceptor
  name: app-sre-github-listener-el
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-app-sre-github-listener-interceptor