---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cincinnati-build-deploy-pipeline-
spec:
  pipelineRef:
    name: cincinnati-build-deploy-pipeline
  params:
    - name: repo-url
      value: 'https://github.com/arilivigni/cincinnati.git'
    - name: rev-id
      value: 'tekton'
    - name: context-dir
      value: './dist'
    - name: image-registry
      value: 'image-registry.openshift-image-registry.svc:5000'
    - name: image-name
      value: 'cincinnati'
    - name: remote-registry
      value: 'quay.io'
    - name: remote-org
      value: 'arilivigni'
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
