---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hive-build-deploy-pipeline-
spec:
  pipelineRef:
    name: hive-build-deploy-pipeline
  params:
    - name: repo-url
      value: 'https://github.com/arilivigni/hive.git'
    - name: rev-id
      value: 'tekton'
    - name: context-dir
      value: '.'
    - name: image-registry
      value: 'image-registry.openshift-image-registry.svc:5000'
    - name: image-name
      value: 'hive'
    - name: name-space
      value: 'hive-cicd'
    - name: remote-registry
      value: 'quay.io'
    - name: remote-org
      value: 'arilivigni'
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
